//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class DBTeknikServisEntities : DbContext
    {
        public DBTeknikServisEntities()
            : base("name=DBTeknikServisEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TBLADMIN> TBLADMIN { get; set; }
        public DbSet<TBLARACLAR> TBLARACLAR { get; set; }
        public DbSet<TBLARIZADETAY> TBLARIZADETAY { get; set; }
        public DbSet<TBLCARI> TBLCARI { get; set; }
        public DbSet<TBLDEPARTMAN> TBLDEPARTMAN { get; set; }
        public DbSet<TBLFATURABILGI> TBLFATURABILGI { get; set; }
        public DbSet<TBLFATURADETAY> TBLFATURADETAY { get; set; }
        public DbSet<TBLGIDER> TBLGIDER { get; set; }
        public DbSet<TBLKATEGORI> TBLKATEGORI { get; set; }
        public DbSet<TBLNOTLARIM> TBLNOTLARIM { get; set; }
        public DbSet<TBLPERSONEL> TBLPERSONEL { get; set; }
        public DbSet<TBLURUN> TBLURUN { get; set; }
        public DbSet<TBLURUNHAREKET> TBLURUNHAREKET { get; set; }
        public DbSet<TBLURUNKABUL> TBLURUNKABUL { get; set; }
        public DbSet<TBLURUNTAKIP> TBLURUNTAKIP { get; set; }
        public DbSet<TBLHAKKIMIZDA> TBLHAKKIMIZDA { get; set; }
        public DbSet<TBLILETISIM> TBLILETISIM { get; set; }
        public DbSet<TBLILCELER> TBLILCELER { get; set; }
        public DbSet<TBLILLER> TBLILLER { get; set; }
    
        public virtual ObjectResult<urunkategori_Result> urunkategori()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<urunkategori_Result>("urunkategori");
        }
    
        public virtual ObjectResult<string> makskategoriurun()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("makskategoriurun");
        }
    
        public virtual ObjectResult<maksurunmarka_Result> maksurunmarka()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<maksurunmarka_Result>("maksurunmarka");
        }
    
        public virtual ObjectResult<maksurunmarka1_Result> maksurunmarka1()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<maksurunmarka1_Result>("maksurunmarka1");
        }
    }
}
