//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLILLER
    {
        public TBLILLER()
        {
            this.TBLILCELER = new HashSet<TBLILCELER>();
        }
    
        public int ILID { get; set; }
        public string ILADI { get; set; }
    
        public virtual ICollection<TBLILCELER> TBLILCELER { get; set; }
    }
}
