//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLKATEGORI
    {
        public TBLKATEGORI()
        {
            this.TBLURUN = new HashSet<TBLURUN>();
        }
    
        public byte ID { get; set; }
        public string AD { get; set; }
    
        public virtual ICollection<TBLURUN> TBLURUN { get; set; }
    }
}
